name: ci

# Run on push and once a week to keep the images from bitrotting and to
# identify issues while no commits are being pushed.
on:
  pull_request:
    branches: [master,main]
  schedule:
    - cron: "52 2 * * 0"
  workflow_dispatch:

# Cancel old PR builds when pushing new commits.
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    name: Build and Install
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 2024.10.0-mach
      - run: zig build test
      - run: zig build apps

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 2024.10.0-mach
      - run: zig fmt --check src/*.zig
